application: e~runcstat
version: 1
runtime: python27
api_version: 1
threadsafe: true

builtins:
- remote_api: on

handlers:
- url: /static
  static_dir: static

- url: /bower_components
  static_dir: bower_components

- url: /.*
  script: main.app

libraries:
- name: jinja2
  version: latest
- name: webapp2
  version: latest
